version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis://redis:6379
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
#  worker:
#    platform: linux/amd64
#    build:
#      context: ./worker
#      dockerfile: Dockerfile
#    depends_on:
#      - redis
#    environment:
#      - REDIS_HOST=redis://redis:6379
#    volumes:
#      - ../simg:/app/simg
#    restart: unless-stopped
  dashboard:
    image: cjlapao/rq-dashboard
    ports:
      - "9181:9181"
    depends_on:
      - redis
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379